Models/dboModels/City.cs
namespace Attractions.Models.dboModels
{
    public class City
    {
        public int Id { get; set; }
        public string CityName { get; set; } = null!;
    }
}

Controllers/MoscowController.cs
using Microsoft.AspNetCore.Mvc;
using Attractions.Models.dtoModels;
using Attractions.Dbcontext;
using System.Diagnostics;
using Attractions.Models;
using Attractions.Models.dboModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;

namespace Attractions.Controllers
{
    public class MoscowController : Controller
    {

        private const string KeyId = "Id";
        private readonly ILogger<HomeController> _logger;
        private readonly dbContext _context;
        public MoscowController(ILogger<HomeController> logger, dbContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
            => View("/Views/City/Moscow/Index.cshtml");
        
        public async Task<IActionResult> RedSquare()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if(id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 7).ToListAsync();

            return View("/Views/City/Moscow/RedSquare.cshtml", feedbacks);
        }
        [HttpPost]
        public IActionResult RedSquare(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("RedSquare");
        }
        public async Task<IActionResult> BolshoiTheater()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 8).ToListAsync();
            return View("/Views/City/Moscow/BolshoiTheater.cshtml", feedbacks);
        }
        [HttpPost]
        public IActionResult BolshoiTheater(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("BolshoiTheater");
        }

        public async Task<IActionResult> VDNH()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 9).ToListAsync();
            return View("/Views/City/Moscow/VDNH.cshtml", feedbacks);
        }
        [HttpPost]
        public IActionResult VDNH(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("VDNH");
        }

        public async Task<IActionResult> MoscowCity()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 10).ToListAsync();
            return View("/Views/City/Moscow/MoscowCity.cshtml", feedbacks);
        }
        [HttpPost]
        public IActionResult MoscowCity(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("MoscowCity");
        }

        public async Task<IActionResult> MoscowZoo()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 11).ToListAsync();
            return View("/Views/City/Moscow/MoscowZoo.cshtml", feedbacks);
        }
        [HttpPost]
        public IActionResult MoscowZoo(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("MoscowZoo");
        }
        public async Task<IActionResult> MoscowMetro()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 12).ToListAsync();
            return View("/Views/City/Moscow/MoscowMetro.cshtml", feedbacks);
        }
        [HttpPost]
        public IActionResult MoscowMetro(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("MoscowMetro");
        }
        public void AddFeedbackToDataBase(dtoFeedback feedback)
        {
            if (feedback.NameSender != null)
            {
                _context.Feedback.Add(GetFullFeedback(feedback));
                _context.SaveChanges();
            }
        }
        public Feedback GetFullFeedback(dtoFeedback feedback)
            => new Feedback
            {
                Id_Sight = feedback.Id_Sight,
                NameSender = feedback.NameSender,
                FeedBackText = feedback.FeedBackText,
                Ball = feedback.Ball,
                Id_User = int.TryParse(Request.Cookies[KeyId], out var tempUserID) ? tempUserID : null,
                fb_datatime = DateTime.UtcNow,
            };
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
            => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/City/Moscow/BolshoiTheater.cshtml
@{
    ViewData["Title"] = "Большой театр";
}
@model IEnumerable<Attractions.Models.dboModels.Feedback>
<div class="img-container my-5">
    <img class="city-main-img" src="/Image/Bolshoi TheaterHeader.png" />
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Немного из истории</h2>
        <p>
            Большой театр — это старейший музыкальный театр России, расположенный в центре Москвы на Театральной площади.
            Основан в 1776 году, полное название — Государственный Академический Большой театр оперы и балета России.
            В театре представлены различные жанры, включая балет и оперу. <br>
        </p>
        <h2 class="kiwi-maru-regular text-center my-5">Время работы</h2>
        <p>
            Для посещения Большого театра необходимо приобрести билеты в кассах театра, на официальном сайте или у 
            туристических агентств. Билеты обычно продаются за несколько месяцев до представления.<br>
        </p>
        <p><b>Адрес: Театральная площадь, 1</b></p>
        <div class="btn-container">
            <a href="https://bolshoi.ru/" class="btn btn-2">Купить билет</a>
        </div>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Фотографии
        </h2>
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Bolshoi Theater1.png" alt="Большой театр 1">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Bolshoi Theater2.png" alt="Большой театр 2">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Bolshoi Theater3.png" alt="Большой театр 3">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Bolshoi Theater4.png" alt="Большой театр 4">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Bolshoi Theater5.png" alt="Большой театр 5">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Bolshoi Theater6.png" alt="Большой театр 6">
    </div>
</div>

<div class="img-container mb-5">
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Поделитесь мнением</h2>


        <form method="post" class="form-reviews" asp-controller="Moscow" asp-action="BolshoiTheater">
            <div class="form-group">
                <input type="hidden" name="Id_Sight" value="8" />
                <br><label>Представтесь</label><br>
                <input class="mb-2" name="NameSender" value="@ViewData["FIO"]" type="text" @(string.IsNullOrEmpty(ViewData["FIO"]?.ToString()) ? "" : "readonly") />
                <textarea class="form-control" placeholder="Ваш отзыв" name="FeedBackText"></textarea>
                <div class="stars">
                    <div class="star-group">
                        <input type="radio" class="star" id="one" value="1" name="Ball" checked>
                        <input type="radio" class="star" id="two" value="2" name="Ball">
                        <input type="radio" class="star" id="three" value="3" name="Ball">
                        <input type="radio" class="star" id="four" value="4" name="Ball">
                        <input type="radio" class="star" id="five" value="5" name="Ball">
                    </div>

                </div>
                <button class="btn-container btn btn-2" type="submit">
                    Отправить
                </button>
            </div>
        </form>
        <div>
            <h2 class="kiwi-maru-regular text-center my-5">Отзывы</h2>
            <table class="table table-info">

                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.NameSender</td>
                            <td>@mes.fb_datatime.ToShortDateString()</td>
                            <td>@mes.FeedBackText</td>
                            <td>@mes.Ball</td>
                        </tr>
                    }
                </tbody>
                <caption>>:^) Всего: @Model.Count()</caption>
            </table>
        </div>

    </div>
</div>

Views/City/Moscow/Index.cshtml
@{
    ViewData["Title"] = "Москва";
}

<div class="img-container my-5">
    <img class="city-main-img" src="/Image/Moscow.png" />
    <div class="mx-5">
        <h1 class="kiwi-maru-regular text-center my-5">Немного из истории</h1>
        <p>
            Первое упоминание о городе в летописях относится к 1147 году. Первоначально Москва была деревянной. 
            В ходе междоусобных войн осенью 1176 года её сожгли вместе с окрестными сёлами, но впоследствии город был восстановлен. 
            Московское княжество образовалось в 1263 году. Оно сначала включало только сам город и его окрестности.
        </p>
        <p>
            В XIV — начале XV веков Москва являлась крупным торговым и ремесленным городом. В это время она состояла из Кремля, Китай-города и некоторых сёл.
        </p>
        <p>
            Столицей Русского государства Москва стала в конце XV века при Иване III Васильевиче. Новый статус способствовал экономическому развитию города. 
            Его размеры постепенно увеличивались. В 1712 году столица была перенесена в Санкт-Петербург.
        </p>
        <p>
            В 1918 году Москва стала столицей РСФСР, в 1922 году — столицей СССР.
        </p>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Куда сходить
        </h2>
    </div>
    <div class="item">
        <a asp-controller="Moscow" asp-action="RedSquare">
            <img src="~/Image/Red Square.png" alt="Красная площадь">
            <div class="centered">Красная площадь</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="Moscow" asp-action="BolshoiTheater">
            <img src="~/Image/Bolshoi Theater.png" alt="Большой театр">
            <div class="centered">Большой театр</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="Moscow" asp-action="VDNH">
            <img src="~/Image/VDNH.png" alt="ВДНХ">
            <div class="centered">ВДНХ</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="Moscow" asp-action="MoscowCity">
            <img src="~/Image/Moscow City.png" alt="Москва Сити">
            <div class="centered">Москва Сити</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="Moscow" asp-action="MoscowZoo">
            <img src="~/Image/MoscowZoo.png" alt="Московский зоопарк">
            <div class="centered">Московский зоопарк</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="Moscow" asp-action="MoscowMetro">
            <img src="~/Image/MoscowMetro.png" alt="Московское метро">
            <div class="centered">Московское метро</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
</div>

Views/City/Moscow/MoscowCity.cshtml
@{
    ViewData["Title"] = "Москва Сити";
}
@model IEnumerable<Attractions.Models.dboModels.Feedback>
<div class="img-container my-5">
    <img class="city-main-img" src="/Image/MoscowCityHeader.png" />
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Немного из истории</h2>
        <p>
            Москва-Сити — это современный архитектурный комплекс небоскрёбов из стекла и бетона,
            расположенный на Краснопресненской набережной. Высота зданий варьируется от 27 до 96 этажей.
            Здесь находятся офисы крупных компаний, выставочный центр и разнообразные объекты сферы услуг.
            В Москва-Сити есть три смотровые площадки, с которых открываются потрясающие виды на столицу. <br>
        </p>
        <h2 class="kiwi-maru-regular text-center my-5">Время работы</h2>
        <p>
            Проход к зданиям открыт круглосуточно.<br>
        </p>
        <p><b>Адрес: Пресненская наб., 10, стр. 1</b></p>
        <div class="btn-container">
            <b class="btn btn-2">Вход свободный</b>
        </div>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Фотографии
        </h2>
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowCity1.png" alt="Москва Сити 1">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowCity2.png" alt="Москва Сити 2">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowCity3.png" alt="Москва Сити 3">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowCity4.png" alt="Москва Сити 4">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowCity5.png" alt="Москва Сити 5">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowCity6.png" alt="Москва Сити 6">
    </div>
</div>

<div class="img-container mb-5">
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Поделитесь мнением</h2>


        <form method="post" class="form-reviews" asp-controller="Moscow" asp-action="MoscowCity">
            <div class="form-group">
                <input type="hidden" name="Id_Sight" value="10" />
                <br><label>Представтесь</label><br>
                <input class="mb-2" name="NameSender" value="@ViewData["FIO"]" type="text" @(string.IsNullOrEmpty(ViewData["FIO"]?.ToString()) ? "" : "readonly") />
                <textarea class="form-control" placeholder="Ваш отзыв" name="FeedBackText"></textarea>
                <div class="stars">
                    <div class="star-group">
                        <input type="radio" class="star" id="one" value="1" name="Ball" checked>
                        <input type="radio" class="star" id="two" value="2" name="Ball">
                        <input type="radio" class="star" id="three" value="3" name="Ball">
                        <input type="radio" class="star" id="four" value="4" name="Ball">
                        <input type="radio" class="star" id="five" value="5" name="Ball">
                    </div>

                </div>
                <button class="btn-container btn btn-2" type="submit">
                    Отправить
                </button>
            </div>
        </form>
        <div>
            <h2 class="kiwi-maru-regular text-center my-5">Отзывы</h2>
            <table class="table table-info">

                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.NameSender</td>
                            <td>@mes.fb_datatime.ToShortDateString()</td>
                            <td>@mes.FeedBackText</td>
                            <td>@mes.Ball</td>
                        </tr>
                    }
                </tbody>
                <caption>>:^) Всего: @Model.Count()</caption>
            </table>
        </div>

    </div>
</div>

Views/City/Moscow/MoscowMetro.cshtml
@{
    ViewData["Title"] = "Московское метро";
}
@model IEnumerable<Attractions.Models.dboModels.Feedback>
<div class="img-container my-5">
    <img class="city-main-img" src="/Image/MoscowMetroHeader.png" />
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Немного из истории</h2>
        <p>
            Московское метро — это одна из самых красивых и удобных систем общественного транспорта в мире.
            Оно состоит из 15 линий общей протяжённостью около 450 километров. Самая длинная линия — 
            Большаякольцевая, её длина составляет около 60 километров. Московское метро включает 258 станций,
            среди которых есть станции-дворцы, украшенные витражами, колоннами, пышными люстрами и мозаиками.<br>
        </p>
        <h2 class="kiwi-maru-regular text-center my-5">Время работы</h2>
        <p>
            Музей метро: ежедневно с 10:00 до 18:00<br>
        </p>
        <p><b>Адрес: Деловой центр, второй ярус станции (первый вагон из центра)</b></p>
        <div class="btn-container">
            <a href="https://tour.mosmetro.ru/" class="btn btn-2">Купить билет</a>
        </div>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Фотографии
        </h2>
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowMetro1.png" alt="Московское метро 1">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowMetro2.png" alt="Московское метро 2">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowMetro3.png" alt="Московское метро 3">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowMetro4.png" alt="Московское метро 4">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowMetro5.png" alt="Московское метро 5">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowMetro6.png" alt="Московское метро 6">
    </div>
</div>

<div class="img-container mb-5">
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Поделитесь мнением</h2>
        <form method="post" class="form-reviews" asp-controller="Moscow" asp-action="MoscowMetro">
            <div class="form-group">
                <input type="hidden" name="Id_Sight" value="12" />
                <br><label>Представтесь</label><br>
                <input class="mb-2" name="NameSender" value="@ViewData["FIO"]" type="text" @(string.IsNullOrEmpty(ViewData["FIO"]?.ToString()) ? "" : "readonly") />
                <textarea class="form-control" placeholder="Ваш отзыв" name="FeedBackText"></textarea>
                <div class="stars">
                    <div class="star-group">
                        <input type="radio" class="star" id="one" value="1" name="Ball" checked>
                        <input type="radio" class="star" id="two" value="2" name="Ball">
                        <input type="radio" class="star" id="three" value="3" name="Ball">
                        <input type="radio" class="star" id="four" value="4" name="Ball">
                        <input type="radio" class="star" id="five" value="5" name="Ball">
                    </div>

                </div>
                <button class="btn-container btn btn-2" type="submit">
                    Отправить
                </button>
            </div>
        </form>
        <div>
            <h2 class="kiwi-maru-regular text-center my-5">Отзывы</h2>
            <table class="table table-info">

                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.NameSender</td>
                            <td>@mes.fb_datatime.ToShortDateString()</td>
                            <td>@mes.FeedBackText</td>
                            <td>@mes.Ball</td>
                        </tr>
                    }
                </tbody>
                <caption>>:^) Всего: @Model.Count()</caption>
            </table>
        </div>
    </div>
</div>

Views/City/Moscow/MoscowZoo.cshtml
@{
    ViewData["Title"] = "Московский зоопарк";
}
@model IEnumerable<Attractions.Models.dboModels.Feedback>
<div class="img-container my-5">
    <img class="city-main-img" src="/Image/MoscowZooHeader.png" />
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Немного из истории</h2>
        <p>
            Московский зоопарк — один из старейших зоопарков в Европе, основан в 1864 году.
            Его площадь составляет 21,65 гектара, а количество животных — 10 531 особь
            (по состоянию на 1 января 2019 года). В коллекции зоопарка представлено 1267 видов животных. <br>
            Московский зоопарк входит в десятку самых посещаемых зоопарков мира,
            его ежегодно посещают около 3,8 миллиона человек.<br>
        </p>
        <h2 class="kiwi-maru-regular text-center my-5">Время работы</h2>
        <p>
            Летний график работы: ежедневно с 7:30-21:00<br>
        </p>
        <p><b>Адрес: Большая Грузинская ул., 1, стр. 1, Москва</b></p>
        <div class="btn-container">
            <a href="https://moscowzoo.ru/visitors/tickets" class="btn btn-2">Купить билет</a>
        </div>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Фотографии
        </h2>
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowZoo1.png" alt="Московский зоопарк 1">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowZoo2.png" alt="Московский зоопарк 2">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowZoo3.png" alt="Московский зоопарк 3">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowZoo4.png" alt="Московский зоопарк 4">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowZoo5.png" alt="Московский зоопарк 5">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/MoscowZoo6.png" alt="Московский зоопарк 6">
    </div>
</div>

<div class="img-container mb-5">
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Поделитесь мнением</h2>


        <form method="post" class="form-reviews" asp-controller="Moscow" asp-action="MoscowZoo">
            <div class="form-group">
                <input type="hidden" name="Id_Sight" value="11" />
                <br><label>Представтесь</label><br>
                <input class="mb-2" name="NameSender" value="@ViewData["FIO"]" type="text" @(string.IsNullOrEmpty(ViewData["FIO"]?.ToString()) ? "" : "readonly") />
                <textarea class="form-control" placeholder="Ваш отзыв" name="FeedBackText"></textarea>
                <div class="stars">
                    <div class="star-group">
                        <input type="radio" class="star" id="one" value="1" name="Ball" checked>
                        <input type="radio" class="star" id="two" value="2" name="Ball">
                        <input type="radio" class="star" id="three" value="3" name="Ball">
                        <input type="radio" class="star" id="four" value="4" name="Ball">
                        <input type="radio" class="star" id="five" value="5" name="Ball">
                    </div>

                </div>
                <button class="btn-container btn btn-2" type="submit">
                    Отправить
                </button>
            </div>
        </form>
        <div>
            <h2 class="kiwi-maru-regular text-center my-5">Отзывы</h2>
            <table class="table table-info">

                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.NameSender</td>
                            <td>@mes.fb_datatime.ToShortDateString()</td>
                            <td>@mes.FeedBackText</td>
                            <td>@mes.Ball</td>
                        </tr>
                    }
                </tbody>
                <caption>>:^) Всего: @Model.Count()</caption>
            </table>
        </div>

    </div>
</div>

Views/City/Moscow/RedSquare.cshtml
@{
    ViewData["Title"] = "Красная площадь";
}
@model IEnumerable<Attractions.Models.dboModels.Feedback>
<div class="img-container my-5">
    <img class="city-main-img" src="/Image/Red Square in Moscow.png" />
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Немного из истории</h2>
        <p>
            Московский Кремль — это крепость в центре Москвы, древнейшая часть города и его исторический центр. 
            Он расположен на высоком левом берегу Москвы-реки, Боровицком холме, и является официальной резиденцией 
            президента Российской Федерации.  <br>
            <br>
            Кремль представляет собой неправильный треугольник площадью 27,5 гектара. Южная стена обращена к Москве-реке, 
            северо-западная — к Александровскому саду, а восточная — к Красной площади. В Кремле находятся архитектурные памятники, 
            такие как стены и башни, соборы, дворцовые постройки и площади.
        </p>
        <h2 class="kiwi-maru-regular text-center my-5">Время работы</h2>
        <p>
            Красная площадь в Москве работает круглосуточно.<br>
        </p>
        <p><b>Адрес: Москва, Красная площадь</b></p>
        <div class="btn-container">
            <b class="btn btn-2">Вход свободный</b>
        </div>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Фотографии
        </h2>
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Red Square1.png" alt="Красная площадь 1">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Red Square2.png" alt="Красная площадь 2">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Red Square3.png" alt="Красная площадь 3">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Red Square4.png" alt="Красная площадь 4">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Red Square5.png" alt="Красная площадь 5">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Red Square6.png" alt="Красная площадь 6">
    </div>
</div>

<div class="img-container mb-5">
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Поделитесь мнением</h2>


        <form method="post" class="form-reviews" asp-controller="Moscow" asp-action="RedSquare">
            <div class="form-group">
                <input type="hidden" name="Id_Sight" value="7" />
                <br><label>Представтесь</label><br>
                <input class="mb-2" name="NameSender" value="@ViewData["FIO"]" type="text" @(string.IsNullOrEmpty(ViewData["FIO"]?.ToString()) ? "" : "readonly") />
                <textarea class="form-control" placeholder="Ваш отзыв" name="FeedBackText"></textarea>
                <div class="stars">
                    <div class="star-group">
                        <input type="radio" class="star" id="one" value="1" name="Ball" checked>
                        <input type="radio" class="star" id="two" value="2" name="Ball">
                        <input type="radio" class="star" id="three" value="3" name="Ball">
                        <input type="radio" class="star" id="four" value="4" name="Ball">
                        <input type="radio" class="star" id="five" value="5" name="Ball">
                    </div>

                </div>
                <button class="btn-container btn btn-2" type="submit">
                    Отправить
                </button>
            </div>
        </form>
        <div>
            <h2 class="kiwi-maru-regular text-center my-5">Отзывы</h2>
            <table class="table table-info">

                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.NameSender</td>
                            <td>@mes.fb_datatime.ToShortDateString()</td>
                            <td>@mes.FeedBackText</td>
                            <td>@mes.Ball</td>
                        </tr>
                    }
                </tbody>
                <caption>>:^) Всего: @Model.Count()</caption>
            </table>
        </div>

    </div>
</div>