Models/dboModels/City.cs
namespace Attractions.Models.dboModels
{
    public class City
    {
        public int Id { get; set; }
        public string CityName { get; set; } = null!;
    }
}

Controllers/SaintPetersburgController.cs
using Microsoft.AspNetCore.Mvc;
using Attractions.Models.dtoModels;
using Attractions.Dbcontext;
using System.Diagnostics;
using Attractions.Models;
using Attractions.Models.dboModels;
using Microsoft.EntityFrameworkCore;

namespace Attractions.Controllers
{
    public class SaintPetersburgController : Controller
    {
        private const string KeyId = "Id";
        private readonly ILogger<HomeController> _logger;
        private readonly dbContext _context;
        public SaintPetersburgController(ILogger<HomeController> logger, dbContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult Index() 
            =>  View("/Views/City/SaintPetersburg/Index.cshtml");
        public async Task<IActionResult> Hermitage()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 1).ToListAsync();
            return View("/Views/City/SaintPetersburg/Hermitage.cshtml", feedbacks);
        }
        [HttpPost]
        public IActionResult Hermitage(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return  RedirectToAction("Hermitage");
        }
        public async Task<IActionResult> IsaacCathedral()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 2).ToListAsync();
            return View("/Views/City/SaintPetersburg/IsaacCathedral.cshtml", feedbacks);
        }

        [HttpPost]
        public IActionResult IsaacCathedral(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("IsaacCathedral");
        }

        public async Task<IActionResult> PeterPavelFortress()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 3).ToListAsync();
            return View("/Views/City/SaintPetersburg/PeterPavelFortress.cshtml", feedbacks);
        }

        [HttpPost]
        public IActionResult PeterPavelFortress(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("PeterPavelFortress");
        }

        public async Task<IActionResult> SmolnyCathedral()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 4).ToListAsync();
            return View("/Views/City/SaintPetersburg/SmolnyCathedral.cshtml", feedbacks);
        }

        [HttpPost]
        public IActionResult SmolnyCathedral(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("SmolnyCathedral");
        }

        public async Task<IActionResult> SummerGarden()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 5).ToListAsync();
            return View("/Views/City/SaintPetersburg/SummerGarden.cshtml", feedbacks);
        }

        [HttpPost]
        public IActionResult CruiserAurora(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("CruiserAurora");
        }

        public async Task<IActionResult> CruiserAurora()
        {
            string id = Request.Cookies[KeyId] ?? "";
            if (id != "")
            {
                int UserId = Convert.ToInt32(id);
                User? u = await _context.Users.FindAsync(UserId);
                ViewData["FIO"] = $"{u.FirstName} {u.LastName}";
            }
            List<Feedback> feedbacks = await _context.Feedback.Where(f => f.IsAccepted && f.Id_Sight == 6).ToListAsync();
            return View("/Views/City/SaintPetersburg/CruiserAurora.cshtml", feedbacks);
        }

        [HttpPost]
        public IActionResult SummerGarden(dtoFeedback feedback)
        {
            AddFeedbackToDataBase(feedback);
            return RedirectToAction("SummerGarden");
        }
        public void AddFeedbackToDataBase(dtoFeedback feedback)
        {
            if (feedback.NameSender != null)
            {
                _context.Feedback.Add(GetFullFeedback(feedback));
                _context.SaveChanges();
            }  
        }
        public Feedback GetFullFeedback(dtoFeedback feedback)
            => new Feedback
            {
                Id_Sight = feedback.Id_Sight,
                NameSender = feedback.NameSender,
                FeedBackText = feedback.FeedBackText,
                Ball = feedback.Ball,
                Id_User = int.TryParse(Request.Cookies[KeyId], out var tempUserID) ? tempUserID : null,
                fb_datatime = DateTime.UtcNow,
            };
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
            => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });

    }
}

Views/City/SaintPetersburg/CruiserAurora.cshtml
@{
    ViewData["Title"] = "Крейсер Аврора";
}
@model IEnumerable<Attractions.Models.dboModels.Feedback>
<div class="img-container my-5">
    <img class="city-main-img" src="/Image/cruiser Aurora.png" />
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Немного из истории</h2>
        <p>
            Крейсер «Аврора» — это корабль 1-го ранга Балтийского флота, названный в честь парусного фрегата «Аврора», 
            прославившегося при обороне Петропавловска-Камчатского в годы Крымской войны. Крейсер участвовал в 
            русско-японской и Первой мировой войнах. Во время Октябрьской революции холостой выстрел с «Авроры» послужил 
            сигналом к штурму Зимнего дворца.  <br>
            <br>
            С 1948 года корабль находится на вечной стоянке у Петроградской набережной.
        </p>
        <h2 class="kiwi-maru-regular text-center my-5">Время работы</h2>
        <p>
            Режим работы: с 11:00 до 18:00<br>
            Выходные дни - понедельник, вторник.<br>
        </p>
        <p><b>Адрес: Санкт-Петербург, Петроградская набережная</b></p>
        <div class="btn-container">
            <a href="https://navalmuseum.ru/bay_ticket#text" class="btn btn-2">Купить билет</a>
        </div>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Фотографии
        </h2>
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/cruiser Aurora1.png" alt="Летний сад 1">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/cruiser Aurora2.png" alt="Летний сад 2">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/cruiser Aurora3.png" alt="Летний сад 3">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/cruiser Aurora4.png" alt="Летний сад 4">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/cruiser Aurora5.png" alt="Летний сад 5">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/cruiser Aurora6.png" alt="Летний сад 6">
    </div>
</div>

<div class="img-container mb-5">
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Поделитесь мнением</h2>
        <form method="post" class="form-reviews" asp-controller="SaintPetersburg" asp-action="CruiserAurora">
            <div class="form-group">
                <input type="hidden" name="Id_Sight" value="6" />
                <br><label>Представтесь</label><br>
                <input class="mb-2" name="NameSender" value="@ViewData["FIO"]" type="text" @(string.IsNullOrEmpty(ViewData["FIO"]?.ToString()) ? "" : "readonly") />
                <textarea class="form-control" placeholder="Ваш отзыв" name="FeedBackText"></textarea>
                <div class="stars">
                    <div class="star-group">
                        <input type="radio" class="star" id="one" value="1" name="Ball" checked>
                        <input type="radio" class="star" id="two" value="2" name="Ball">
                        <input type="radio" class="star" id="three" value="3" name="Ball">
                        <input type="radio" class="star" id="four" value="4" name="Ball">
                        <input type="radio" class="star" id="five" value="5" name="Ball">
                    </div>

                </div>
                <button class="btn-container btn btn-2" type="submit">
                    Отправить
                </button>
            </div>
        </form>
        <div>
            <h2 class="kiwi-maru-regular text-center my-5">Отзывы</h2>
            <table class="table table-info">

                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.NameSender</td>
                            <td>@mes.fb_datatime.ToShortDateString()</td>
                            <td>@mes.FeedBackText</td>
                            <td>@mes.Ball</td>
                        </tr>
                    }
                </tbody>
                <caption>>:^) Всего: @Model.Count()</caption>
            </table>
        </div>

    </div>
</div>

Views/City/SaintPetersburg/Hermitage.cshtml
@{
    ViewData["Title"] = "Эрмитаж";
}
@model IEnumerable<Attractions.Models.dboModels.Feedback>
<div class="img-container my-5">
    <img class="city-main-img" src="/Image/ermitazh-top.png" />
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Немного из истории</h2>
        <p>
            Эрмитаж - один из крупнейших и наиболее значимых художественных и
            культурно-исторических музеев мира, расположенный в самом сердце
            Санкт-Петербурга, городе на Неве. <br>
            <br>
            Основанный в 1764 году, Эрмитаж представляет собой обширное собрание
            бесценных произведений искусства, исторических и археологических экспонатов,
            охватывающих тысячелетия человеческой истории.
        </p>
        <h2 class="kiwi-maru-regular text-center my-5">Время работы</h2>
        <p>
            Среда, четверг, воскресенье<br>
            11:00 – 18:00 Последний сеанс: 16:00<br>
            Вторник, пятница, суббота<br>
            11:00 – 20:00 Последний сеанс: 18:00
        </p> 
        <p><b>Адрес: Дворцовая площадь, 2, Санкт-Петербург</b></p>
        <div class="btn-container">
            <a href="https://tickets.hermitagemuseum.org/?id=3&sid=1" class="btn btn-2">Купить билет</a>
        </div>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Фотографии
        </h2>
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/ermitazh1.png" alt="Эрмитаж 1">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/ermitazh2.png" alt="Эрмитаж 2">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/ermitazh3.png" alt="Эрмитаж 3">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/ermitazh4.png" alt="Эрмитаж 4">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/ermitazh5.png" alt="Эрмитаж 5">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/ermitazh6.png" alt="Эрмитаж 6">
    </div>
</div>

<div class="img-container mb-5">
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Поделитесь мнением</h2>
        
        
        <form method="post" class="form-reviews" asp-controller="SaintPetersburg" asp-action="Hermitage">
            <div class="form-group">
                <input type="hidden" name="Id_Sight" value="1" />
                <br><label>Представтесь</label><br>
                <input class="mb-2" name="NameSender" value="@ViewData["FIO"]" type="text" @(string.IsNullOrEmpty(ViewData["FIO"]?.ToString()) ? "" : "readonly") />
                <textarea class="form-control" placeholder="Ваш отзыв" name="FeedBackText"></textarea>
                <div class="stars">
                    <div class="star-group">
                        <input type="radio" class="star" id="one" value="1" name="Ball" checked>
                        <input type="radio" class="star" id="two" value="2" name="Ball">
                        <input type="radio" class="star" id="three" value="3" name="Ball">
                        <input type="radio" class="star" id="four" value="4" name="Ball">
                        <input type="radio" class="star" id="five" value="5" name="Ball">
                    </div>
                    
                </div>
                <button class="btn-container btn btn-2" type="submit" >
                    Отправить
                </button>
            </div>
        </form>
        <div>
            <h2 class="kiwi-maru-regular text-center my-5">Отзывы</h2>
            <table class="table table-info">
                
                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.NameSender</td>
                            <td>@mes.fb_datatime.ToShortDateString()</td>
                            <td>@mes.FeedBackText</td>
                            <td>@mes.Ball</td>
                        </tr>
                    }
                </tbody>
                <caption>>:^) Всего: @Model.Count()</caption>
            </table>
        </div>
        
    </div>
</div>

Views/City/SaintPetersburg/Index.cshtml
@{
    ViewData["Title"] = "Санкт-Петербург";
}

<div class="img-container my-5">
    <img class="city-main-img" src="/Image/Petersburg.png" />
    <div class="mx-5">
        <h1 class="kiwi-maru-regular text-center my-5">Немного из истории</h1>
        <p>
            Санкт-Петербург - это город, расположенный на северо-западе России, на побережье Финского залива. Это один из крупнейших городов страны, с населением более 5 миллионов человек. Санкт-Петербург был основан в 1703 году Петром I и стал столицей Российской империи в 1712 году. За свою историю город пережил множество событий, включая две мировые войны и блокаду во время Второй мировой войны.
        </p>
        <p>
            Сегодня Санкт-Петербург является одним из важнейших культурных, образовательных и научных центров России. В городе расположено множество музеев, театров, парков и других достопримечательностей. Среди них - Эрмитаж, Русский музей, Мариинский театр, Исаакиевский собор, Невский проспект и многие другие.
        </p>
        <p>
            Также Санкт-Петербург известен своими белыми ночами, когда ночь превращается в сумерки на протяжении нескольких недель в июне. Это время года привлекает множество туристов, чтобы увидеть это уникальное явление.
        </p>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Куда сходить
        </h2>
    </div>
    <div class="item">
        <a asp-controller="SaintPetersburg" asp-action="Hermitage">
            <img src="~/Image/zimny.png" alt="Зимний дворец">
            <div class="centered">Зимний дворец</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="SaintPetersburg" asp-action="IsaacCathedral">
            <img src="~/Image/isakiy.png" alt="Исаакиевский собор">
            <div class="centered">Исаакиевский собор</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="SaintPetersburg" asp-action="PeterPavelFortress">
            <img src="~/Image/petropavlovskaya.png" alt="Петропавловская крепость">
            <div class="centered">Петропавловская крепость</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="SaintPetersburg" asp-action="SmolnyCathedral">
            <img src="~/Image/smolniy.png" alt="Смольный собор">
            <div class="centered">Смольный собор</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="SaintPetersburg" asp-action="SummerGarden">
            <img src="~/Image/Summer garden_min.png" alt="Летний сад">
            <div class="centered">Летний сад</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
    <div class="item">
        <a asp-controller="SaintPetersburg" asp-action="CruiserAurora">
            <img src="~/Image/avrora.png" alt="Крейсер Аврора">
            <div class="centered">Крейсер Аврора</div>
            <span class="bottom-right badge bg-success rounded-pill">4.0</span>
        </a>
    </div>
</div>

Views/City/SaintPetersburg/IsaacCathedral.cshtml
@{
    ViewData["Title"] = "Исаакиевский собор";
}
@model IEnumerable<Attractions.Models.dboModels.Feedback>
<div class="img-container my-5">
    <img class="city-main-img" src="/Image/IsaacCathedral.jpg" />
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Немного из истории</h2>
        <p>
            Исаакиевский собор – неотъемлемая часть архитектурного облика Санкт-Петербурга. Наряду с
            Медным всадником, Петропавловской крепостью и шпилем Адмиралтейства он является одним
            из символов города на Неве. <br>
            <br>
            Собор освящен во имя святого преподобного Исаакия Далматского, в день поминовения
            которого родился основатель города царь Петр I. Существующий ныне собор является
            четвертым храмом, построенным в Петербурге в ознаменование дня рождения Петра.
        </p>
        <h2 class="kiwi-maru-regular text-center my-5">Время работы</h2>
        <p><u>Музей-памятник «Исаакиевский собор»</u></p>
        <p>
            С 10:00 до 18:00<br>
            (кассы с 10:00 до 17:30)<br>
            Выходной день – среда<br>
            11:00 – 20:00 Последний сеанс: 18:00<br>
        </p>
        <p><u>Колоннада Исаакиевского собора</u></p>
        <p>
            С 10:00 до 18:00<br>
            (с 01 мая по 30 сентября – без выходных; с 01 октября по 30 апреля выходной день –  третья среда месяца<br>
        </p>
        <p><b>Адрес: Исаакиевская площадь, 4, Санкт-Петербург</b></p>
        <div class="btn-container">
            <a href="https://isaak.ticketnet.ru/?id=1&sid=1" class="btn btn-2">Купить билет</a>
        </div>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Фотографии
        </h2>
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Saint Isaac's Cathedral1.png" alt="Исаакиевский собор 1">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Saint Isaac's Cathedral2.png" alt="Исаакиевский собор 2">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Saint Isaac's Cathedral3.png" alt="Исаакиевский собор 3">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Saint Isaac's Cathedral4.png" alt="Исаакиевский собор 4">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Saint Isaac's Cathedral5.png" alt="Исаакиевский собор 5">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Saint Isaac's Cathedral6.png" alt="Исаакиевский собор 6">
    </div>
</div>

<div class="img-container mb-5">
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Поделитесь мнением</h2>


        <form method="post" class="form-reviews" asp-controller="SaintPetersburg" asp-action="IsaacCathedral">
            <div class="form-group">
                <input type="hidden" name="Id_Sight" value="2" />
                <br><label>Представтесь</label><br>
                <input class="mb-2" name="NameSender" value="@ViewData["FIO"]" type="text" @(string.IsNullOrEmpty(ViewData["FIO"]?.ToString()) ? "" : "readonly") />
                <textarea class="form-control" placeholder="Ваш отзыв" name="FeedBackText"></textarea>
                <div class="stars">
                    <div class="star-group">
                        <input type="radio" class="star" id="one" value="1" name="Ball" checked>
                        <input type="radio" class="star" id="two" value="2" name="Ball">
                        <input type="radio" class="star" id="three" value="3" name="Ball">
                        <input type="radio" class="star" id="four" value="4" name="Ball">
                        <input type="radio" class="star" id="five" value="5" name="Ball">
                    </div>

                </div>
                <button class="btn-container btn btn-2" type="submit">
                    Отправить
                </button>
            </div>
        </form>
        <div>
            <h2 class="kiwi-maru-regular text-center my-5">Отзывы</h2>
            <table class="table table-info">

                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.NameSender</td>
                            <td>@mes.fb_datatime.ToShortDateString()</td>
                            <td>@mes.FeedBackText</td>
                            <td>@mes.Ball</td>
                        </tr>
                    }
                </tbody>
                <caption>>:^) Всего: @Model.Count()</caption>
            </table>
        </div>

    </div>
</div>

Views/City/SaintPetersburg/PeterPavelFortress.cshtml
@{
    ViewData["Title"] = "Петропавловская крепость";
}
@model IEnumerable<Attractions.Models.dboModels.Feedback>
<div class="img-container my-5">
    <img class="city-main-img" src="/Image/Peter-Pavel Fortress.png" />
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Немного из истории</h2>
        <p>
            Петропавловская крепость была основана в 1703 году по приказу царя Петра I. 
            Она была заложена на Заячьем острове реки Невы и должна была защищать завоевания 
            России в ходе Северной войны.Планировка крепости соответствует фортификационной 
            системе С. Ле Претр де Вобана.  <br>
            <br>
            Первые укрепления были дерево-земляными, затем они были заменены кирпичными стенами. 
            В 1712 году был построен Петропавловский собор, который стал центром архитектурного 
            ансамбля крепости.
        </p>
        <h2 class="kiwi-maru-regular text-center my-5">Время работы</h2>
        <p>
            Музей работает ежедневно, кроме среды. <br>
            Внимание! С 1 мая по 30 сентября по средам открыты
            Петропавловский собор с Великокняжеской усыпальницей и тюрьма
            Трубецкого бастиона. <br>
        </p>
        <p><b>Адрес: Территория Петропавловская крепость, 3Ч, Санкт-Петербург</b></p>
        <div class="btn-container">
            <a href="https://www.spbmuseum.ru/themuseum/visitors/buy_ticket.php" class="btn btn-2">Купить билет</a>
        </div>
    </div>
</div>
<div class="items py-5 text-center">
    <div class="item-center">
        <h2 class="kiwi-maru-regular text-center">
            Фотографии
        </h2>
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Peter-Pavel Fortress1.png" alt="Петропавловская крепость 1">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Peter-Pavel Fortress2.png" alt="Петропавловская крепость 2">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Peter-Pavel Fortress3.png" alt="Петропавловская крепость 3">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Peter-Pavel Fortress4.png" alt="Петропавловская крепость 4">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Peter-Pavel Fortress5.png" alt="Петропавловская крепость 5">
    </div>
    <div class="item-foto-n-h">
        <img src="~/Image/Peter-Pavel Fortress6.png" alt="Петропавловская крепость 6">
    </div>
</div>

<div class="img-container mb-5">
    <div class="mx-5">
        <h2 class="kiwi-maru-regular text-center my-5">Поделитесь мнением</h2>


        <form method="post" class="form-reviews" asp-controller="SaintPetersburg" asp-action="PeterPavelFortress">
            <div class="form-group">
                <input type="hidden" name="Id_Sight" value="3" />
                <br><label>Представтесь</label><br>
                <input class="mb-2" name="NameSender" value="@ViewData["FIO"]" type="text" @(string.IsNullOrEmpty(ViewData["FIO"]?.ToString()) ? "" : "readonly") />
                <textarea class="form-control" placeholder="Ваш отзыв" name="FeedBackText"></textarea>
                <div class="stars">
                    <div class="star-group">
                        <input type="radio" class="star" id="one" value="1" name="Ball" checked>
                        <input type="radio" class="star" id="two" value="2" name="Ball">
                        <input type="radio" class="star" id="three" value="3" name="Ball">
                        <input type="radio" class="star" id="four" value="4" name="Ball">
                        <input type="radio" class="star" id="five" value="5" name="Ball">
                    </div>

                </div>
                <button class="btn-container btn btn-2" type="submit">
                    Отправить
                </button>
            </div>
        </form>
        <div>
            <h2 class="kiwi-maru-regular text-center my-5">Отзывы</h2>
            <table class="table table-info">

                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.NameSender</td>
                            <td>@mes.fb_datatime.ToShortDateString()</td>
                            <td>@mes.FeedBackText</td>
                            <td>@mes.Ball</td>
                        </tr>
                    }
                </tbody>
                <caption>>:^) Всего: @Model.Count()</caption>
            </table>
        </div>

    </div>
</div>